name: "Push"
description: "Push docker images to registry"

runs:
  using: "composite"
  steps:
    - name: Login to docker registry
      run: echo "${{ env.REGISTRY_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ env.REGISTRY_USER }} --password-stdin
      shell: bash

    - name: Push to docker registry
      run: docker-compose push
      shell: bash
